# Generated by Django 5.0 on 2023-12-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConjVerb',
            fields=[
                ('translation', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('infinitive', models.CharField(max_length=30)),
                ('sg_Ip_form', models.CharField(max_length=30)),
                ('sg_IIp_form', models.CharField(max_length=30)),
                ('sg_IIIp_form', models.CharField(max_length=30)),
                ('pl_Ip_form', models.CharField(max_length=30)),
                ('pl_IIp_form', models.CharField(max_length=30)),
                ('pl_IIIp_form', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
