# Generated by Django 5.0 on 2024-03-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0002_alter_conjverb_unique_together_conjverb_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=30)),
                ('infinitive', models.CharField(max_length=30)),
                ('prateritum', models.CharField(max_length=30)),
                ('partizip2', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('translation', 'infinitive')},
            },
        ),
    ]
