# Generated by Django 5.0 on 2024-03-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0003_remove_conjverb_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjverb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
