# Generated by Django 5.0 on 2024-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0005_remove_conjverb_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RectionVerb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('translation', models.CharField(max_length=30)),
                ('infinitive', models.CharField(max_length=30)),
                ('preposition', models.CharField(max_length=30)),
                ('case', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('translation', 'infinitive')},
            },
        ),
    ]
